USE InLock_Games_Manha
GO

CREATE PROC SP_ListarTodosUsuarios
AS
	BEGIN
			SELECT	APELIDO AS NICKMANE
					,EMAIL AS EMAIL
					,NOME_TIPO AS 'TIPO DO USUÁRIO'
			FROM			TBL_USUARIOS
			INNER JOIN		TBL_TiposUsuario
			ON				TBL_USUARIOS.ID_TipoUsuario = TBL_TiposUsuario.ID_TipoUsuario
	END
GO

CREATE PROC SP_ListarTodosEstudios
AS
	BEGIN
			SELECT	NOME_ESTUDIO
			FROM	TBL_ESTUDIOS
	END
GO

CREATE PROC SP_ListarJogosEstudios
AS
	BEGIN
			SELECT	NOME_JOGO			AS 'NOME DO JOGO'
					,DESCRICAO			AS 'DESCRIÇÃO'
					,DATA_LANCAMENTO	AS 'DATA DE LANÇAMENTO'
					,VALOR				AS 'PREÇO'
					,NOME_ESTUDIO		AS 'ESTÚDIO'
			FROM TBL_JOGOS
			INNER JOIN TBL_ESTUDIOS ON TBL_JOGOS.ID_ESTUDIO = TBL_ESTUDIOS.ID_ESTUDIO
	END
GO