CREATE DATABASE InLock_Games_Manha
GO

USE InLock_Games_Manha
GO

CREATE TABLE TBL_ESTUDIOS
(
	ID_ESTUDIO		INT PRIMARY KEY IDENTITY
	,NOME_ESTUDIO	VARCHAR(255) UNIQUE NOT NULL
);
GO

CREATE TABLE TBL_JOGOS
(
	ID_JOGO				INT PRIMARY KEY IDENTITY
	,NOME_JOGO			VARCHAR(255)	NOT NULL
	,DESCRICAO			TEXT
	,DATA_LANCAMENTO	DATE
	,VALOR				FLOAT			NOT NULL
	,ID_ESTUDIO			INT FOREIGN KEY REFERENCES TBL_ESTUDIOS (ID_ESTUDIO)
);
GO

CREATE TABLE TBL_TiposUsuario
(
	ID_TipoUsuario		INT PRIMARY KEY
	,NOME_TIPO			VARCHAR(255) UNIQUE NOT NULL
);
GO

CREATE TABLE TBL_USUARIOS
(
	ID_USUARIO			INT PRIMARY KEY IDENTITY
	,APELIDO			VARCHAR(255) NOT NULL
	,EMAIL				VARCHAR(255) UNIQUE NOT NULL
	,SENHA				VARCHAR(255) NOT NULL
	,PERMISSAO			VARCHAR(255) NOT NULL
	,ID_TipoUsuario		INT FOREIGN KEY REFERENCES TBL_TiposUsuario (ID_TipoUsuario)
);
GO 